### ISSUE TITLE
Material description fetching failing

### ISSUE THREAD

**Issue by i307698** [SAP/cloud-sdk-java#769]
### Describe the Bug

We use com.sap.cloud.sdk.s4hana.datamodel.odata.services.DefaultProductMasterService to fetch the material description for a particular material. This call is failing with an error message saying that "communication failed".__

We got this response from your team and changed accordingly.
Your original ticket did not mention kubernetes.

Have you considered our documentation on Gardener..?
https://sap.github.io/cloud-sdk/docs/java/environments/kubernetes-gardener

or Kyma..?
https://sap.github.io/cloud-sdk/docs/java/environments/kubernetes-kyma

Please open a new issue.

After implementing connectivity proxy and binding it to our app, I tried the API which was supposed to get the material description again.
It gave me this problem -

{"msg":"S4 Material description fetch failed with error: com.sap.cloud.sdk.cloudplatform.thread.exception.ThreadContextExecutionException: com.sap.cloud.sdk.cloudplatform.connectivity.exception.HttpClientInstantiationException: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationAccessException: Unable to create an HttpClient from the provided destination. The destination is supposed to target an on-premise system but lacks the correct proxy configuration. Please check the application logs for further details.","tenant_id":"ac76728d-e6de-493a-8eb7-209c1eb1cf84","level":"INFO","written_ts":"1742797238460961395","logger":"com.sap.qm.psp.extensions.apiservice.imp.S4HDescriptionService","correlation_id":"489ad550-cb0f-445b-9e44-d51e4401e729","written_at":"2025-03-24T06:20:38.460Z","thread":"http-nio-8080-exec-1","type":"log"}

Please let me know if there are any additional changes required from my side.

My GitHub link is -

https://github.tools.sap/DigitalManufacturing/psp-core-ms

The link to the PR -

https://github.tools.sap/DigitalManufacturing/psp-core-ms/commit/bb61921fff3168bc29b6bf30e53f002bc76a4c35

Thanks,
Saurabh

### Steps to Reproduce

1. Create a PSP from S4 or using tools like Postman.
2. Call goes to S4 to get the material description using DefaultProductMasterService
3. This call fails saying communication failed.

### Expected Behavior

Material description is fetched without issues.

### Used Versions

Java - 17 and
Maven version - 3.8.6
SAP Cloud SDK version:
com.sap.cloud.sdk.s4hana s4hana-all 4.32.0
- Spring Boot or CAP version: 3.3.4
<cds.services.version>3.2.0</cds.services.version>
<cloud.sdk.version>5.11.0</cloud.sdk.version>

### Code Examples

```java
// Your code here
```

### Log File

<details><summary>Log file</summary>
...
</details>

### Affected Development Phase

Getting Started

### Impact

No Impact

**Comment by Jonas-Isr** [comment]
Hi @i307698, 

you are using our Cloud SDK on version `4.32.0`. The end of life/end of support for versions 4.x was [2 years ago](https://sap.github.io/cloud-sdk/docs/java/release-policy) already. I would thus recommend to update to version 5 of the SDK. You can find a detailed update guide [in our docs](https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps).

We can continue to help and support you once you updated. In the best case scenario, the problem is solved through the update.

Best,
Jonas

**Comment by i307698** [comment]
Hello @Jonas-Isr 
I followed the documentation and tried generating the OData client that is compatible with the OData VDM the SAP Cloud SDK provided in version 4.
But I can see nothing created in my output folder.

Here is the branch where I pushed my changes-
https://github.tools.sap/DigitalManufacturing/psp-core-ms/tree/material_desc

Please let me know if I am missing something.
Thanks,
Saurabh

**Comment by Jonas-Isr** [comment]
Hi @i307698,

what exactly were you doing when you tried generating the OData client? Did you follow the steps outlined [here](https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps#generate-and-use-your-own-odata-clients) and/or [here](https://sap.github.io/cloud-sdk/docs/java/features/odata/vdm-generator#using-the-odata-generator)?

I looked into the repository you linked and saw that you are still using version `4.32.0` [here](https://github.tools.sap/DigitalManufacturing/psp-core-ms/blob/80c6b96b1882ef25e8d0cfee56dd67b679b7d781/srv/pom.xml#L327) even though you are trying to generate the OData client. Is this on purpose?

Additionally, we *strongly* advice to not mix different version of our SDK in the same application. It might lead to unexpected behaviour or errors. I saw that you are using three different versions (`5.11.0`, `5.14.0` and `5.17.0`) [here](https://github.tools.sap/DigitalManufacturing/psp-core-ms/blob/80c6b96b1882ef25e8d0cfee56dd67b679b7d781/srv/pom.xml#L184). Refer to [this guide](https://sap.github.io/cloud-sdk/docs/java/guides/manage-dependencies#the-sap-cloud-sdk-bill-of-material) for more information.

I hope this helps!
Best,
Jonas

**Comment by i307698** [comment]
Hi @Jonas-Isr ,

What I intended to do was to generate classes like "ECCDescriptionService" which were provided as a part of s4hana-all dependency. But now that this dependancy has been removed, I was trying to generate these classes so that we can develop a typed data client around it.

I have made the changes to the same branch and have made it clean but I have still not got the classes that belonged to "com.sap.qm.psp.models" package.

https://github.tools.sap/DigitalManufacturing/psp-core-ms/tree/material_desc

Thanks,
Saurabh

**Comment by newtork** [comment]
It looks like you are **not** discussing the originally observed issue 

> We use com.sap.cloud.sdk.s4hana.datamodel.odata.services.DefaultProductMasterService to fetch the material description for a particular material. This call is failing with an error message saying that "communication failed".__

> `{"msg":"S4 Material description fetch failed with error: com.sap.cloud.sdk.cloudplatform.thread.exception.ThreadContextExecutionException: com.sap.cloud.sdk.cloudplatform.connectivity.exception.HttpClientInstantiationException: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationAccessException: Unable to create an HttpClient from the provided destination. The destination is supposed to target an on-premise system but lacks the correct proxy configuration. Please check the application logs for further details.","tenant_id":"ac76728d-e6de-493a-8eb7-209c1eb1cf84","level":"INFO","written_ts":"1742797238460961395","logger":"com.sap.qm.psp.extensions.apiservice.imp.S4HDescriptionService","correlation_id":"489ad550-cb0f-445b-9e44-d51e4401e729","written_at":"2025-03-24T06:20:38.460Z","thread":"http-nio-8080-exec-1","type":"log"}`


---

Now you are talking about generator plugin usage. Please create a new issue, if you face problems. But make sure you read everything necessary here in our documentation:

https://sap.github.io/cloud-sdk/docs/java/features/odata/vdm-generator


I briefly looked into your branch.

```
<inputDirectory>${project.basedir}/src/main/resources/edmx</inputDirectory>
```

* You may want to check whether EDMX files actually in this path.

```
<outputDirectory>${project.build.directory}/vdm</outputDirectory>
```

* Please understand the setting above will generate files under `/target/vdm/`. You can move the files into your source directory manually, or automatically make Maven aware of this generated-sources folder for compilation.
  
  [In our internal sample project](https://github.com/SAP/cloud-sdk-java/blob/main/datamodel/odata/odata-api-sample/pom.xml#L152) we generate the code directly in `/src/main/java`, However all files will be deleted from this folder if `deleteOutputDirectory=true` which is true for our project and your branch. Probably not what you want. Instead your original `/target/vdm/` approach looks safer.

Maybe this helps already, and we can close this issue.

If you still have questions regarding code generation, unfortunately I will **not** give further instructions until a dedicated issue has been created.

**Comment by i307698** [comment]
Hi @newtork ,

We made a lot of changes to the way that we were accessing the S4 on premise endpoint.

We made changes to completely align with documentation for K8s https://sap.github.io/cloud-sdk/docs/java/environments/kubernetes-kyma

Also, we aligned all the SDK versions.

Now after making these changes, we test the scenario where we call S4 systems, we get the following errors:

com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationAccessException: Unable to resolve connectivity service binding. More than one service bindings found that match Connectivity.

Here is the stack trace for the same:

0 = {StackTraceElement@17974} "com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination$Builder.build(DefaultHttpDestination.java:1003)"
1 = {StackTraceElement@17975} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationServiceFactory.handleHttpDestination(DestinationServiceFactory.java:113)"
2 = {StackTraceElement@17976} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationServiceFactory.fromDestinationServiceV1Response(DestinationServiceFactory.java:65)"
3 = {StackTraceElement@17977} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationService.loadAndParseDestination(DestinationService.java:141)"
4 = {StackTraceElement@17978} "com.sap.cloud.sdk.cloudplatform.connectivity.GetOrComputeSingleDestinationCommand.lambda$prepareCommand$0(GetOrComputeSingleDestinationCommand.java:66)"
5 = {StackTraceElement@17979} "io.vavr.control.Try.of(Try.java:74)"
6 = {StackTraceElement@17980} "io.vavr.control.Try.ofSupplier(Try.java:91)"
7 = {StackTraceElement@17981} "com.sap.cloud.sdk.cloudplatform.connectivity.GetOrComputeSingleDestinationCommand.execute(GetOrComputeSingleDestinationCommand.java:153)"
8 = {StackTraceElement@17982} "io.vavr.control.Try.flatMapTry(Try.java:489)"
9 = {StackTraceElement@17983} "io.vavr.control.Try.flatMap(Try.java:471)"
10 = {StackTraceElement@17984} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationService$Cache.getOrComputeDestination(DestinationService.java:866)"
11 = {StackTraceElement@17985} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationService.tryGetDestination(DestinationService.java:124)"
12 = {StackTraceElement@17986} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationLoaderChain.tryGetDestination(DestinationLoaderChain.java:85)"
13 = {StackTraceElement@17987} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationLoader.tryGetDestination(DestinationLoader.java:33)"
14 = {StackTraceElement@17988} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationAccessor.tryGetDestination(DestinationAccessor.java:120)"
15 = {StackTraceElement@17989} "com.sap.cloud.sdk.cloudplatform.connectivity.DestinationAccessor.getDestination(DestinationAccessor.java:97)"
16 = {StackTraceElement@17990} "com.sap.qm.psp.extensions.apiservice.enhancers.ApiEnhancerImpl.updateDescription(ApiEnhancerImpl.java:734)"
17 = {StackTraceElement@17991} "com.sap.qm.psp.extensions.apiservice.imp.ApiServiceImpl.onCreateASupplierIssueProcesses(ApiServiceImpl.java:144)"
18 = {StackTraceElement@17992} "com.sap.qm.psp.extensions.apiservice.hooks.ASupplierIssueProcesses.onCreateASupplierIssueProcesses(ASupplierIssueProcesses.java:67)"
19 = {StackTraceElement@17993} "com.sap.cds.services.impl.handlerregistry.HandlerRegistryTools$DescribedHandler.process(HandlerRegistryTools.java:165)"
20 = {StackTraceElement@17994} "com.sap.cds.services.impl.ServiceImpl.lambda$createOnHandlerChain$4(ServiceImpl.java:269)"
21 = {StackTraceElement@17995} "com.sap.cds.services.impl.ServiceImpl.dispatch(ServiceImpl.java:236)"
22 = {StackTraceElement@17996} "com.sap.cds.services.impl.ServiceImpl.emit(ServiceImpl.java:177)"
23 = {StackTraceElement@17997} "com.sap.cds.services.ServiceDelegator.emit(ServiceDelegator.java:33)"
24 = {StackTraceElement@17998} "com.sap.cds.services.utils.services.AbstractCqnService.run(AbstractCqnService.java:64)"
25 = {StackTraceElement@17999} "com.sap.cds.services.impl.cds.AbstractCdsDefinedService.lambda$run$1(AbstractCdsDefinedService.java:59)"
26 = {StackTraceElement@18000} "com.sap.cds.services.impl.cds.AbstractCdsDefinedService.runProjected(AbstractCdsDefinedService.java:92)"
27 = {StackTraceElement@18001} "com.sap.cds.services.impl.cds.AbstractCdsDefinedService.run(AbstractCdsDefinedService.java:59)"
28 = {StackTraceElement@18002} "com.sap.cds.adapter.odata.v4.processors.CdsProcessor.post(CdsProcessor.java:457)"
29 = {StackTraceElement@18003} "com.sap.cds.adapter.odata.v4.processors.CdsProcessor.delegateRequest(CdsProcessor.java:232)"
30 = {StackTraceElement@18004} "com.sap.cds.adapter.odata.v4.processors.CdsProcessor.lambda$processRequest$1(CdsProcessor.java:156)"
31 = {StackTraceElement@18005} "com.sap.cds.services.impl.runtime.RequestContextRunnerImpl.lambda$run$3(RequestContextRunnerImpl.java:213)"
32 = {StackTraceElement@18006} "com.sap.cds.services.impl.runtime.RequestContextRunnerImpl.run(RequestContextRunnerImpl.java:272)"
33 = {StackTraceElement@18007} "com.sap.cds.services.impl.runtime.RequestContextRunnerImpl.run(RequestContextRunnerImpl.java:212)"
34 = {StackTraceElement@18008} "com.sap.cds.adapter.odata.v4.processors.CdsProcessor.processRequest(CdsProcessor.java:153)"
35 = {StackTraceElement@18009} "com.sap.cds.adapter.odata.v4.processors.CdsProcessor.lambda$processRequest$0(CdsProcessor.java:144)"
36 = {StackTraceElement@18010} "com.sap.cds.services.impl.runtime.ChangeSetContextRunnerImpl.open(ChangeSetContextRunnerImpl.java:70)"
37 = {StackTraceElement@18011} "com.sap.cds.services.impl.runtime.ChangeSetContextRunnerImpl.run(ChangeSetContextRunnerImpl.java:49)"
38 = {StackTraceElement@18012} "com.sap.cds.adapter.odata.v4.processors.CdsProcessor.processRequest(CdsProcessor.java:143)"
39 = {StackTraceElement@18013} "com.sap.cds.adapter.odata.v4.processors.AbstractODataProcessor.processRequest(AbstractODataProcessor.java:164)"
40 = {StackTraceElement@18014} "com.sap.cds.adapter.odata.v4.processors.FastODataProcessor.processEntity(FastODataProcessor.java:100)"
41 = {StackTraceElement@18015} "com.sap.cds.adapter.odata.v4.processors.OlingoProcessor.createEntity(OlingoProcessor.java:162)"
42 = {StackTraceElement@18016} "org.apache.olingo.server.core.ODataDispatcher.handleEntityCollectionDispatching(ODataDispatcher.java:563)"
43 = {StackTraceElement@18017} "org.apache.olingo.server.core.ODataDispatcher.handleEntityDispatching(ODataDispatcher.java:524)"
44 = {StackTraceElement@18018} "org.apache.olingo.server.core.ODataDispatcher.handleResourceDispatching(ODataDispatcher.java:154)"
45 = {StackTraceElement@18019} "org.apache.olingo.server.core.ODataDispatcher.dispatch(ODataDispatcher.java:120)"
46 = {StackTraceElement@18020} "org.apache.olingo.server.core.ODataHandlerImpl.processInternal(ODataHandlerImpl.java:174)"
47 = {StackTraceElement@18021} "org.apache.olingo.server.core.ODataHandlerImpl.process(ODataHandlerImpl.java:95)"
48 = {StackTraceElement@18022} "org.apache.olingo.server.core.ODataHttpHandlerImpl.process(ODataHttpHandlerImpl.java:80)"
49 = {StackTraceElement@18023} "org.apache.olingo.server.core.ODataHttpHandlerImpl.process(ODataHttpHandlerImpl.java:94)"
50 = {StackTraceElement@18024} "com.sap.cds.adapter.odata.v4.CdsODataV4Servlet.lambda$service$0(CdsODataV4Servlet.java:132)"
51 = {StackTraceElement@18025} "com.sap.cds.services.impl.runtime.RequestContextRunnerImpl.lambda$run$3(RequestContextRunnerImpl.java:213)"
52 = {StackTraceElement@18026} "com.sap.cds.services.impl.runtime.RequestContextRunnerImpl.run(RequestContextRunnerImpl.java:272)"
53 = {StackTraceElement@18027} "com.sap.cds.services.impl.runtime.RequestContextRunnerImpl.run(RequestContextRunnerImpl.java:212)"
54 = {StackTraceElement@18028} "com.sap.cds.adapter.odata.v4.CdsODataV4Servlet.service(CdsODataV4Servlet.java:90)"
55 = {StackTraceElement@18029} "jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)"
56 = {StackTraceElement@18030} "com.sap.cds.framework.spring.config.adapter.ServletAdapterRestController.handleRequest(ServletAdapterRestController.java:30)"
57 = {StackTraceElement@18031} "org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)"
58 = {StackTraceElement@18032} "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)"
59 = {StackTraceElement@18033} "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)"
60 = {StackTraceElement@18034} "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)"
61 = {StackTraceElement@18035} "org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)"
62 = {StackTraceElement@18036} "jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)"
63 = {StackTraceElement@18037} "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)"
64 = {StackTraceElement@18038} "jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)"
65 = {StackTraceElement@18039} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)"
66 = {StackTraceElement@18040} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)"
67 = {StackTraceElement@18041} "org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)"
68 = {StackTraceElement@18042} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)"
69 = {StackTraceElement@18043} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)"
70 = {StackTraceElement@18044} "com.sap.cloud.sdk.cloudplatform.servletjakarta.RequestAccessorFilter.lambda$doFilter$0(RequestAccessorFilter.java:56)"
71 = {StackTraceElement@18045} "com.sap.cloud.sdk.cloudplatform.thread.ThreadContextExecutor.lambda$execute$1(ThreadContextExecutor.java:260)"
72 = {StackTraceElement@18046} "com.sap.cloud.sdk.cloudplatform.thread.ThreadContextExecutor.call(ThreadContextExecutor.java:293)"
73 = {StackTraceElement@18047} "com.sap.cloud.sdk.cloudplatform.thread.ThreadContextExecutor.execute(ThreadContextExecutor.java:259)"
74 = {StackTraceElement@18048} "com.sap.cloud.sdk.cloudplatform.servletjakarta.RequestAccessorFilter.doFilter(RequestAccessorFilter.java:56)"
75 = {StackTraceElement@18049} "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)"
76 = {StackTraceElement@18050} "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)"
77 = {StackTraceElement@18051} "org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)"
78 = {StackTraceElement@18052} "org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)"
79 = {StackTraceElement@18053} "org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)"
80 = {StackTraceElement@18054} "org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)"
81 = {StackTraceElement@18055} "org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)"
82 = {StackTraceElement@18056} "org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)"
83 = {StackTraceElement@18057} "org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)"
84 = {StackTraceElement@18058} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)"
85 = {StackTraceElement@18059} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)"
86 = {StackTraceElement@18060} "org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)"
87 = {StackTraceElement@18061} "org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)"
88 = {StackTraceElement@18062} "org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)"
89 = {StackTraceElement@18063} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)"
90 = {StackTraceElement@18064} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)"
91 = {StackTraceElement@18065} "org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)"
92 = {StackTraceElement@18066} "org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)"
93 = {StackTraceElement@18067} "org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)"
94 = {StackTraceElement@18068} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)"
95 = {StackTraceElement@18069} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)"
96 = {StackTraceElement@18070} "org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)"
97 = {StackTraceElement@18071} "org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)"
98 = {StackTraceElement@18072} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)"
99 = {StackTraceElement@18073} "org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)"

Here is the link to our code:

https://github.tools.sap/DigitalManufacturing/psp-core-ms/blob/master/srv/src/main/java/com/sap/qm/psp/extensions/apiservice/imp/S4HDescriptionService.java

The code where the Destination is getting accessed is:

https://github.tools.sap/DigitalManufacturing/psp-core-ms/blob/master/srv/src/main/java/com/sap/qm/psp/extensions/apiservice/enhancers/ApiEnhancerImpl.java

Thanks,
Saurabh

**Comment by newtork** [comment]
> Unable to resolve connectivity service binding. More than one service bindings found that match Connectivity.

You have more than one service binding for connectivity.

Please debug/investigate the contents of...
```java
List<ServiceBinding> connectivityBindings =
    DefaultServiceBindingAccessor.getInstance()
        .getServiceBindings()
        .stream()
        .filter(b -> Optional.of(ServiceIdentifier.CONNECTIVITY).equals(b.getServiceIdentifier()))
        .toList();
```

I cannot tell whether this configuration is correct, but having two occurrences of "connectivity" does look strange...

![Image](https://github.com/user-attachments/assets/4559c1b2-f7a4-430d-9652-af1918da3ef6)

**Comment by newtork** [comment]
I was reminded by a colleague that maybe the issue is using `DestinationAccessor` API, when instead -according to docs- you should use `DefaultHttpDestination.builder` API:
https://sap.github.io/cloud-sdk/docs/java/environments/kubernetes-kyma#executing-requests
